[package]
name = "pocker_front"

version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.22.0", features = ["csr"] }
yew-hooks = "0.4.0"
web-sys = {version ="0.3", features = ["HtmlTextAreaElement"]}
